### ISSUE TITLE
250MB Executable Feels Excessively Large

### ISSUE THREAD

**Issue by sylumer** [saschiwy/HeicConverter#1]
I was looking for a Windows command line utility for converting HEIC files. I came across this repo, but is it really the case that this command line tool, based on a less that 100 line Python script, plus a handful of libraries really compiles to be 250 MB!! That feels extremely heavy for such a utility.

![image](https://github.com/saschiwy/HeicConverter/assets/3868841/fe6af1cf-33e2-4cb8-b21f-d16a435dd9af)

**Comment by saschiwy** [comment]
Hi sylumer, thanks for the comment.

You are quite right. Very big. But it's a executable with all required components, like an the python interpreter, as well as an imaging library which can do much more.

Of course one could exclude all not required parts of those third party library. I don´t think, that this is a real issue, since there is no functional problem. 

However, I hope the tool serves you well.

**Comment by saschiwy** [comment]
FileSize is now only 18 MB
