### ISSUE TITLE
VirusTotal and And Windows defender is detecting binaries as virus why ?

### ISSUE THREAD

**Issue by coolb0y** [saschiwy/HeicConverter#12]

**Comment by saschiwy** [comment]
Hi @coolb0y 

I really have no clue, I checked on another PC i have, with windows defender and there is no threat found. On Virus Total I got 6 of 56 systems showing a trojan warning. I do not know why, I assume because the tool searches for files. This is a requirement to find the files to convert. 

In case you doubt my intention I recommend to either check the code and compile the software yourself or to not use it. I ensure you I put not a trojan inside the tool. However, I used some open source libraries which I did not check.

Best Sascha
